version: "3.9"

services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "8080:8080"
      - "8888:8888"
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.dev.toml:/etc/traefik/traefik.toml"

  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bot_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: ./api
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    volumes:
      - ./api:/code
    expose:
      - 5000
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres_db:5432/bot_db
    depends_on:
      - postgres_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
      - "traefik.http.routers.api-http.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api-http.entrypoints=http"

  frontend:
    build: ./frontend
    command: npm run serve
    volumes:
      - ./frontend:/code
    expose:
      - 80
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres_db:5432/bot_db
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend-http.rule=Host(`m8bot.localhost`)"
      - "traefik.http.routers.frontend-http.entrypoints=http"

  bot:
    build: ./bot
    command: bash -c "python main.py"
    volumes:
      - ./bot:/code
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres_db:5432/bot_db
    depends_on:
      - api