[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[api]
insecure = true

[log]
level = "DEBUG"

[accessLog]

[tracing]

[providers]
  [providers.docker]
    exposedByDefault = false